### ISSUE TITLE
2023 CFP : CSS tout cassé

### ISSUE THREAD

**Issue by hugolpz** [capitoledulibre/capitoledulibre.org#12]
Hello @slestang @fantomid @Linkid @lporcheron ,

![Screenshot from 2023-10-16 10-31-48](https://github.com/capitoledulibre/capitoledulibre.org/assets/1420189/97623e70-6de9-4304-9520-2634980de557)
![Screenshot from 2023-10-16 10-32-01](https://github.com/capitoledulibre/capitoledulibre.org/assets/1420189/1b86be2f-80f4-4fe1-bc0e-71f1700a518f)

Comme le fichier css est absent, une page 404 de type mine txt/html est servie, qui plante.

- https://cfp.capitoledulibre.org/cdl-2023/talk/review/K7TNRJBFDTF9AEUZNPERZCFXTKAHGKHB
- https://cfp.capitoledulibre.org/cdl-2023/me/mails/

**Comment by lporcheron** [comment]
Merci @hugolpz pour le ticket. Je viens de corriger le problème.
