### ISSUE TITLE
Page d'accueil difficile à lire

### ISSUE THREAD

**Issue by astranchet** [capitoledulibre/capitoledulibre.org#13]
Le texte de la page d'accueil "Capitole du Libre 2023 18 & 19 novembre, ENSEEIHT, Toulouse" se superpose à une image très graphiquement chargée. Et le texte "Week-end dédié au logiciel libre ...." est écrit en gris clair, sur une zone gris claire de la photo ; rendant le tout difficile à lire.

Je recommande une de ces stratégies https://www.smashingmagazine.com/2023/08/designing-accessible-text-over-images-part1/ (par exemple, un overlay sur l'image pour la rendre moins prégnante) (et potentiellement une image moins "touffue" en terme d'information)

**Comment by lporcheron** [comment]
Bonjour @astranchet 
Merci pour votre retour et les suggestions. Ce n'est pas encore parfait, mais j'ai appliqué un overlay, ça devrait être mieux :)
