### ISSUE TITLE
Dépôt non à jour

### ISSUE THREAD

**Issue by sdinot** [capitoledulibre/capitoledulibre.org#15]
Bonjour,

Le bouton de la page d'accueil n'étant pas à jour (il annonce le 31 juillet comme échéance de la soumission des propositions de conférences) :

![image](https://github.com/user-attachments/assets/c20151a3-018e-48aa-a5e9-0fe89f419271)

J'ai voulu vous pousser une petite PR, mais je me suis aperçu que le dépôt publié ne correspond pas au site qui est en ligne. Les dernières modifications n'ont pas été poussées sur GitHub.

Je vous en remercie par avance

**Comment by lporcheron** [comment]
Merci pour le retour que j'ai eu sur twitter en parallèle, et du coup on vient de le corriger et de pousser le code à jour sur GitHub :)
merci !
