### ISSUE TITLE
https://github.com/capitoledulibre/capitoledulibre.org/blob/main/pages/village-associatif.tsx date de 2023 est n'est pas à jour

### ISSUE THREAD

**Issue by lhirlimann** [capitoledulibre/capitoledulibre.org#19]
On ne connaît donc pas le programme pour les stands associatifs.

**Comment by lhirlimann** [comment]
bon, je n'ai pas trouvé les stands dans pretalx, pour faire la PR, désolé

**Comment by lhirlimann** [comment]
poke @lporcheron si tu me dit ou trouvé l'info je te fais la PR

**Comment by lporcheron** [comment]
Yes, je viens de mettre à jour. L'info est pas publique sur pretalx :(.
