### ISSUE TITLE
2 créneaux ont un souci d'affichage

### ISSUE THREAD

**Issue by erikmd** [capitoledulibre/capitoledulibre.org#8]
Bonjour,

je viens de voir sur https://capitoledulibre.org/programme/ 2 soucis d'affichage, peut-être liés aux méta-données des créneaux ?
( https://cfp.capitoledulibre.org/cdl-2022/talk/XDQK77/ ; https://cfp.capitoledulibre.org/cdl-2022/talk/X8X8YZ/ )

## souci 1.

![2022-11-16_00-59-39_Screenshot_bug1](https://user-images.githubusercontent.com/10367254/202050162-3f372049-d087-4128-bda4-dad1b9c50001.png)

## souci 2.

![2022-11-16_00-59-56_Screenshot_bug2](https://user-images.githubusercontent.com/10367254/202050174-23c5f072-7db5-4e98-9960-3f4485f73169.png)

**Comment by lporcheron** [comment]
Ah merci beaucoup, un petit changement hier soir avait provoqué ce souci. Il est désormais corrigé. Merci pour le retour détaillé 👍
